# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calendartest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSCalendar'

  # Pods for calendartest

  target 'calendartestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'calendartestUITests' do
    # Pods for testing
  end

end
